-- 1호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 1, '신창', '1408');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 2, '온양온천', '1407');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 3, '배방', '1405');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 4, '아산', '1403');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 5, '쌍용', '1402');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 6, '봉명', '1401');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 7, '천안', '1728');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 8, '두정', '1727');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 9, '직산', '1726');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 10, '성환', '1725');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 11, '평택', '1724');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 12, '평택지제', '1723');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 13, '서정리', '1722');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 14, '송탄', '1721');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 15, '진위', '1720');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 16, '오산', '1719');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 17, '오산대', '1718');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 18, '세마', '1717');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 19, '병점', '1716');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 20, '세류', '1715');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 21, '수원', '1713');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 22, '화서', '1712');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 23, '성균관대', '1711');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 24, '의왕', '1710');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 25, '당정', '1729');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 26, '군포', '1709');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 27, '금정', '1708');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 28, '명학', '1707');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 29, '안양', '1706');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 30, '관악', '1705');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 31, '석수', '1704');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 32, '금천구청', '1703');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 33, '독산', '1714');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 34, '가산디지털단지', '1702');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 35, '구로', '1701');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 36, '신도림', '1007');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 37, '영등포', '1006');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 38, '신길', '1032');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 39, '대방', '1005');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 40, '노량진', '1004');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 41, '용산', '1003');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 42, '남영', '1002');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 43, '서울역', '150');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 44, '시청', '151');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 45, '종각', '152');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 46, '종로3가', '153');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 47, '종로5가', '154');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 48, '동대문', '155');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 49, '동묘앞', '159');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 50, '신설동', '156');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 51, '제기동', '157');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 52, '청량리', '158');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 53, '회기', '1015');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 54, '외대앞', '1016');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 55, '신이문', '1017');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 56, '석계', '1018');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 57, '광운대', '1019');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 58, '월계', '1020');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 59, '녹천', '1021');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 60, '창동', '1022');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 61, '방학', '1901');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 62, '도봉', '1902');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 63, '도봉산', '1903');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 64, '망월사', '1904');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 65, '회룡', '1905');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 66, '의정부', '1906');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 67, '가능', '1907');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 68, '녹양', '1908');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 69, '양주', '1909');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 70, '덕계', '1910');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 71, '덕정', '1911');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 72, '지행', '1912');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 73, '동두천중앙', '1913');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 74, '보산', '1914');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 75, '동두천', '1915');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 0, 76, '소요산', '1916');

insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 1, '인천', '1812');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 2, '동인천', '1811');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 3, '도원', '1817');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 4, '제물포', '1810');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 6, '도화', '1823');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 7, '주안', '1809');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 8, '간석', '1816');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 9, '동암', '1808');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 10, '백운', '1807');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 11, '부평', '1806');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 12, '부개', '1815');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 13, '송내', '1805');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 14, '중동', '1822');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 15, '부천', '1804');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 16, '소사', '1814');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 17, '역곡', '1803');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 18, '온수', '1821');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 19, '오류동', '1802');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 20, '개봉', '1801');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 21, '구일', '1813');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 1, 22, '구로', '1701');

insert into subway_line (line, subline, seq, station_id, external_code) values(1, 2, 1, '서동탄', '1749');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 2, 2, '병점', '1716');

insert into subway_line (line, subline, seq, station_id, external_code) values(1, 3, 1, '광명', '1750');
insert into subway_line (line, subline, seq, station_id, external_code) values(1, 3, 2, '금천구청', '1703');

-- 2호선 리스트
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 1, '시청','을지로입구','충정로', '201');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 2, '을지로입구','을지로3가','시청', '202');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 3, '을지로3가','을지로4가','을지로입구', '203');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 4, '을지로4가','동대문역사문화공원','을지로3가', '204');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 5, '동대문역사문화공원','신당','을지로4가', '205');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 6, '신당','상왕십리','동대문역사문화공원', '206');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 7, '상왕십리','왕십리','신당', '207');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 8, '왕십리','한양대','상왕십리', '208');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 9, '한양대','뚝섬','왕십리', '209');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 10, '뚝섬','성수','한양대', '210');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 11, '성수','건대입구','뚝섬', '211');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 12, '건대입구','구의','성수', '212');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 13, '구의','강변','건대입구', '213');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 14, '강변','잠실나루','구의', '214');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 15, '잠실나루','잠실','강변', '215');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 16, '잠실','잠실새내','잠실나루', '216');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 17, '잠실새내','종합운동장','잠실', '217');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 18, '종합운동장','삼성','잠실새내', '218');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 19, '삼성','선릉','종합운동장', '219');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 20, '선릉','역삼','삼성', '220');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 21, '역삼','강남','선릉', '221');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 22, '강남','교대','역삼', '222');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 23, '교대','서초','강남', '223');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 24, '서초','방배','교대', '224');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 25, '방배','사당','서초', '225');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 26, '사당','낙성대','방배', '226');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 27, '낙성대','서울대입구','사당', '227');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 28, '서울대입구','봉천','낙성대', '228');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 29, '봉천','신림','서울대입구', '229');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 30, '신림','신대방','봉천', '230');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 31, '신대방','구로디지털단지','신림', '231');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 32, '구로디지털단지','대림','신대방', '232');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 33, '대림','신도림','구로디지털단지', '233');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 34, '신도림','문래','대림', '234');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 35, '문래','영등포구청','신도림', '235');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 36, '영등포구청','당산','문래', '236');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 37, '당산','합정','영등포구청', '237');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 38, '합정','홍대입구','당산', '238');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 39, '홍대입구','신촌','합정', '239');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 40, '신촌','이대','홍대입구', '240');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 41, '이대','아현','신촌', '241');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 42, '아현','충정로','이대', '242');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 0, 43, '충정로','시청','아현', '243');

insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 1, 1, '성수', '', '용답', '211');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 1, 2, '용답','성수','신답', '244');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 1, 3, '신답','용답','용두', '245');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 1, 4, '용두','신답','신설동', '250');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 1, 5, '신설동','용두', '', '246');

insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 2, 1, '까치산','','신정네거리', '200');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 2, 2, '신정네거리','까치산','양천구청', '249');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 2, 3, '양천구청','신정네거리','도림천', '248');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 2, 4, '도림천','양천구청','신도림', '247');
insert into subway_line (line, subline, seq, station_id, prev_station_id, next_station_id, external_code) values(2, 2, 5, '신도림','도림천','', '234');


-- 3호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 1, '대화', '1958');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 2, '주엽', '1957');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 3, '정발산', '1956');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 4, '마두', '1955');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 5, '백석', '1954');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 6, '대곡', '1953');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 7, '화정', '1952');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 8, '원당', '1951');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 9, '원흥', '1948');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 10, '삼송', '1950');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 11, '지축', '309');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 12, '구파발', '310');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 13, '연신내', '311');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 14, '불광', '312');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 15, '녹번', '313');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 16, '홍제', '314');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 17, '무악재', '315');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 18, '독립문', '316');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 19, '경복궁', '317');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 20, '안국', '318');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 21, '종로3가', '319');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 22, '을지로3가', '320');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 23, '충무로', '321');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 24, '동대입구', '322');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 25, '약수', '323');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 26, '금호', '324');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 27, '옥수', '325');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 28, '압구정', '326');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 29, '신사', '327');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 31, '잠원', '328');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 32, '고속터미널', '329');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 33, '교대', '330');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 34, '남부터미널', '331');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 35, '양재', '332');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 36, '매봉', '333');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 37, '도곡', '334');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 38, '대치', '335');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 39, '학여울', '336');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 40, '대청', '337');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 41, '일원', '338');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 42, '수서', '339');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 43, '가락시장', '340');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 44, '경찰병원', '341');
insert into subway_line (line, subline, seq, station_id, external_code) values(3, 0, 45, '오금', '342');


-- 4호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 1, '당고개', '409');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 2, '상계', '410');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 3, '노원', '411');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 4, '창동', '412');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 5, '쌍문', '413');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 6, '수유', '414');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 7, '미아', '415');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 8, '미아사거리', '416');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 9, '길음', '417');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 10, '성신여대입구', '418');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 11, '한성대입구', '419');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 12, '혜화', '420');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 13, '동대문', '421');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 14, '동대문역사문화공원', '422');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 15, '충무로', '423');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 16, '명동', '424');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 17, '회현', '425');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 18, '서울역', '426');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 19, '숙대입구', '427');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 20, '삼각지', '428');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 21, '신용산', '429');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 22, '이촌', '430');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 23, '동작', '431');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 24, '총신대입구', '432');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 25, '사당', '433');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 26, '남태령', '434');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 27, '선바위', '1450');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 28, '경마공원', '1451');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 29, '대공원', '1452');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 30, '과천', '1453');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 31, '정부과천청사', '1454');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 32, '인덕원', '1455');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 33, '평촌', '1456');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 34, '범계', '1457');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 35, '금정', '1458');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 36, '산본', '1751');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 37, '수리산', '1763');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 38, '대야미', '1752');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 39, '반월', '1753');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 40, '상록수', '1754');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 41, '한대앞', '1755');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 42, '중앙', '1756');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 43, '고잔', '1757');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 44, '초지', '1758');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 45, '안산', '1759');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 46, '신길온천', '1760');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 47, '정왕', '1761');
insert into subway_line (line, subline, seq, station_id, external_code) values(4, 0, 48, '오이도', '1762');

-- 5호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 1, '방화', '2511');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 2, '개화산', '2512');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 3, '김포공항', '2513');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 4, '송정', '2514');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 5, '마곡', '2515');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 6, '발산', '2516');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 7, '우장산', '2517');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 8, '화곡', '2518');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 9, '까치산', '2519');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 10, '신정', '2520');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 11, '목동', '2521');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 12, '오목교', '2522');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 13, '양평', '2523');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 14, '영등포구청', '2524');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 15, '영등포시장', '2525');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 16, '신길', '2526');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 17, '여의도', '2527');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 18, '여의나루', '2528');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 19, '마포', '2529');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 20, '공덕', '2530');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 21, '애오개', '2531');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 22, '충정로', '2532');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 23, '서대문', '2533');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 24, '광화문', '2534');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 25, '종로3가', '2535');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 26, '을지로4가', '2536');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 27, '동대문역사문화공원', '2537');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 28, '청구', '2538');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 29, '신금호', '2539');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 30, '행당', '2540');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 31, '왕십리', '2541');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 32, '마장', '2542');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 33, '답십리', '2543');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 34, '장한평', '2544');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 35, '군자', '2545');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 36, '아차산', '2546');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 37, '광나루', '2547');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 38, '천호', '2548');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 39, '강동', '2549');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 40, '길동', '2550');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 41, '굽은다리', '2551');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 42, '명일', '2552');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 43, '고덕', '2553');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 44, '상일동', '2554');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 45, '강일', '2562');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 46, '미사', '2563');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 47, '하남풍산', '2564');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 48, '하남시청', '2565');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 0, 49, '하남검단산', '2566');

insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 1, '강동', '2549');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 2, '둔촌동', '2555');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 3, '올림픽공원', '2556');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 4, '방이', '2557');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 5, '오금', '2558');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 6, '개롱', '2559');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 7, '거여', '2560');
insert into subway_line (line, subline, seq, station_id, external_code) values(5, 1, 8, '마천', '2561');

-- 6호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 1, '응암', '2611');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 2, '역촌', '2612');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 3, '불광', '2613');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 4, '독바위', '2614');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 5, '연신내', '2615');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 6, '구산', '2616');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 7, '응암', '2611');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 8, '새절', '2617');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 9, '증산', '2618');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 10, '디지털미디어시티', '2619');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 11, '월드컵경기장', '2620');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 12, '마포구청', '2621');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 13, '망원', '2622');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 14, '합정', '2623');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 15, '상수', '2624');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 16, '광흥창', '2625');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 17, '대흥', '2626');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 18, '공덕', '2627');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 19, '효창공원앞', '2628');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 20, '삼각지', '2629');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 21, '녹사평', '2630');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 22, '이태원', '2631');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 23, '한강진', '2632');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 24, '버티고개', '2633');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 25, '약수', '2634');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 26, '청구', '2635');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 27, '신당', '2636');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 28, '동묘앞', '2637');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 29, '창신', '2638');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 30, '보문', '2639');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 31, '안암', '2640');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 32, '고려대', '2641');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 33, '월곡', '2642');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 34, '상월곡', '2643');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 35, '돌곶이', '2644');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 36, '석계', '2645');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 37, '태릉입구', '2646');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 38, '화랑대', '2647');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 39, '봉화산', '2648');
insert into subway_line (line, subline, seq, station_id, external_code) values(6, 0, 40, '신내', '2649');

-- 7호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 1, '장암', '2711');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 2, '도봉산', '2712');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 3, '수락산', '2713');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 4, '마들', '2714');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 5, '노원', '2715');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 6, '중계', '2716');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 7, '하계', '2717');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 8, '공릉', '2718');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 9, '태릉입구', '2719');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 10, '먹골', '2720');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 11, '중화', '2721');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 12, '상봉', '2722');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 13, '면목', '2723');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 14, '사가정', '2724');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 15, '용마산', '2725');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 16, '중곡', '2726');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 17, '군자', '2727');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 18, '어린이대공원', '2728');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 19, '건대입구', '2729');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 20, '뚝섬유원지', '2730');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 21, '청담', '2731');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 22, '강남구청', '2732');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 23, '학동', '2733');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 24, '논현', '2734');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 25, '반포', '2735');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 26, '고속터미널', '2736');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 27, '내방', '2737');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 28, '이수', '2738');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 29, '남성', '2739');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 30, '숭실대입구', '2740');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 31, '상도', '2741');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 32, '장승배기', '2742');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 33, '신대방삼거리', '2743');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 34, '보라매', '2744');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 35, '신풍', '2745');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 36, '대림', '2746');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 37, '남구로', '2747');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 38, '가산디지털단지', '2748');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 39, '철산', '2749');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 40, '광명사거리', '2750');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 41, '천왕', '2751');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 42, '온수', '2752');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 43, '까치울', '2753');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 44, '부천종합운동장', '2754');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 45, '춘의', '2755');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 46, '신중동', '2756');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 47, '부천시청', '2757');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 48, '상동', '2758');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 49, '삼산체육관', '2759');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 50, '굴포천', '2760');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 51, '부평구청', '2761');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 52, '산곡', '3762');
insert into subway_line (line, subline, seq, station_id, external_code) values(7, 0, 53, '석남', '3763');

-- 8호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 1, '암사', '2811');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 2, '천호', '2812');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 3, '강동구청', '2813');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 4, '몽촌토성', '2814');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 5, '잠실', '2815');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 6, '석촌', '2816');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 7, '송파', '2817');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 8, '가락시장', '2818');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 9, '문정', '2819');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 10, '장지', '2820');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 11, '복정', '2821');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 12, '산성', '2822');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 13, '남한산성입구', '2823');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 14, '단대오거리', '2824');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 15, '신흥', '2825');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 16, '수진', '2826');
insert into subway_line (line, subline, seq, station_id, external_code) value(8, 0, 17, '모란', '2827');

-- 9호선 리스트
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 1, '개화', '4101');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 2, '김포공항', '4102');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 3, '공항시장', '4103');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 4, '신방화', '4104');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 5, '마곡나루', '4105');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 6, '양천향교', '4106');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 7, '가양', '4107');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 8, '증미', '4108');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 9, '등촌', '4109');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 10, '염창', '4110');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 11, '신목동', '4111');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 12, '선유도', '4112');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 13, '당산', '4113');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 14, '국회의사당', '4114');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 15, '여의도', '4115');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 16, '샛강', '4116');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 17, '노량진', '4117');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 18, '노들', '4118');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 19, '흑석', '4119');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 20, '동작', '4120');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 21, '구반포', '4121');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 22, '신반포', '4122');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 23, '고속터미널', '4123');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 24, '사평', '4124');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 25, '신논현', '4125');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 26, '언주', '4126');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 27, '선정릉', '4127');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 28, '삼성중앙', '4128');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 29, '봉은사', '4129');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 30, '종합운동장', '4130');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 31, '삼전', '4131');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 32, '석촌고분', '4132');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 33, '석촌', '4133');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 34, '송파나루', '4134');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 35, '한성백제', '4135');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 36, '올림픽공원', '4136');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 37, '둔촌오륜', '4137');
insert into subway_line (line, subline, seq, station_id, external_code) values (9, 0, 38, '중앙보훈병원', '4138');
