INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('종각','Jonggak','02-6110-1311','서울특별시 종로구 종로 지하 55 (종로1가)', 100, 300);
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('서울역','Seoul Station','02-6110-1331','서울특별시 중구 세종대로 지하 2 (남대문로 5가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('시청','City Hall','02-6110-1321','서울특별시 중구 세종대로 지하 101 (정동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('종로3가','Jongno 3(sam)-ga','02-6110-1301','서울특별시 종로구 종로 지하 129 (종로3가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('종로5가','Jongno 5(o)-ga','02-6110-1291','서울특별시 종로구 종로 지하 216  (종로5가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('동대문','Dongdaemun','02-6110-1281','서울특별시 종로구 종로 지하 302 (창신동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신설동','Sinseol-dong','02-6110-1261','서울특별시 동대문구 왕산로 지하 1 (신설동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('제기동','Jegi-dong','02-6110-1251','서울특별시 동대문구 왕산로 지하 93 (제기동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('청량리','Cheongnyangni','02-6110-1241','서울특별시 동대문구 왕산로 지하 205(전농동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('동묘앞','Dongmyo','02-6110-1271','서울특별시 종로구 종로 359 (숭인동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('까치산','Kkachisan','02-6311-5181','서울특별시 강서구 강서로 지하54 (화곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('을지로입구','Euljiro 1(il)-ga','02-6110-2021','서울특별시 중구 을지로 지하 42 (을지로1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('을지로3가','Euljiro 3(sam)-ga','02-6110-2031','서울특별시 중구 을지로 지하 106 (을지로3가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('을지로4가','Euljiro 4(sa)-ga','02-6110-2041','서울특별시 중구 을지로 지하 178 (을지로4가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('동대문역사문화공원','Dongdaemun History  Culture Park','02-6110-2051','서울특별시 중구 을지로 지하 279 (을지로7가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신당','Sindang','02-6110-2061','서울특별시 중구 퇴계로 지하 431-1 (신당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상왕십리','Sangwangsimni','02-6110-2071','서울특별시 성동구 왕십리로 지하 374 (하왕십리동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('왕십리','Wangsimni','02-6110-2081','서울특별시 성동구 왕십리로 지하300 (행당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('한양대','Hanyang Univ.','02-6110-2091','서울특별시 성동구 왕십리로 206 (행당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('뚝섬','Ttukseom','02-6110-2101','서울특별시 성동구 아차산로 18 (성수동1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('성수','Seongsu','02-6110-2111','서울특별시 성동구 아차산로 100 (성수동2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('건대입구','Konkuk Univ.','02-6110-2121','서울특별시 광진구 아차산로 243 (화양동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('구의','Guui','02-6110-2131','서울특별시 광진구 아차산로 384-1 (구의동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('강변','Gangbyeon','02-6110-2141','서울특별시 광진구 강변역로 53 (구의동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('잠실나루','Jamsillaru','02-6110-2151','서울특별시 송파구 오금로 20 (신천동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('잠실','Jamsil','02-6110-2161','서울특별시 송파구 올림픽로 지하 265 (잠실동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('잠실새내','Jamsilsaenae','02-6110-2171','서울특별시 송파구 올림픽로 지하 140 (잠실동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('종합운동장','Sports Complex','02-6110-2181','서울특별시 송파구 올림픽로 지하 23 (잠실동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('삼성','Samseong','02-6110-2191','서울특별시 강남구 테헤란로 지하 538 (삼성동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('역삼','Yeoksam','02-6110-2211','서울특별시 강남구 테헤란로 지하 156 (역삼동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('강남','Gangnam','02-6110-2221','서울특별시 강남구 강남대로 지하 397 (역삼동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('교대','Seoul Nat`l Univ. of Education','02-6110-2231','서울특별시 서초구 서초대로 지하 294 (서초동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('서초','Seocho','02-6110-2241','서울특별시 서초구 서초대로 지하 233 (서초동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('방배','Bangbae','02-6110-2251','서울특별시 서초구 방배로 지하 80 (방배동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('사당','Sadang','02-6110-2261','서울특별시 동작구 남부순환로 지하 2089 (사당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('낙성대','Nakseongdae','02-6110-2271','서울특별시 관악구 남부순환로 지하 1928 (봉천동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('서울대입구','Seoul Nat`l Univ.','02-6110-2281','서울특별시 관악구 남부순환로 지하 1822 (봉천동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('봉천','Bongcheon','02-6110-2291','서울특별시 관악구 남부순환로 지하 1721 (봉천동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신림','Sillim','02-6110-2301','서울특별시 관악구 남부순환로 지하 1614 (신림동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신대방','Sindaebang','02-6110-2311','서울특별시 동작구 대림로 2 (신대방동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('구로디지털단지','Guro Digital Complex','02-6110-2321','서울특별시 구로구 도림천로 477 (구로동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('대림','Daerim','02-6110-2331','서울 구로구 구로6동 125-66', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신도림','Sindorim','02-6110-2341','서울특별시 구로구 새말로 지하 117-21 (신도림동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('문래','Mullae','02-6110-2351','서울특별시 영등포구 당산로 지하 28 (문래동3가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('영등포구청','Yeongdeungpo-gu Office','02-6110-2361','서울특별시 영등포구 당산로 지하 121 (당산동3가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('당산','Dangsan','02-6110-2371','서울특별시 영등포구 당산로 229 (당산동 6가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('합정','Hapjeong','02-6110-2381','서울특별시 마포구 양화로 지하 55 (서교동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('홍대입구','Hongik Univ.','02-6110-2391','서울특별시 마포구 양화로 지하160 (동교동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신촌','Sinchon','02-6110-2401','서울특별시 마포구 신촌로 지하 90 (노고산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('이대','Ewha Womans Univ.','02-6110-2411','서울특별시 마포구 신촌로 지하 180 (염리동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('아현','Ahyeon','02-6110-2421','서울특별시 마포구 신촌로 지하 270 (아현동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('충정로','Chungjeongno','02-6110-2431','서울특별시 서대문구 서소문로 지하 17 (충정로3가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('용답','Yongdap','02-6110-1341','서울특별시 성동구 용답길 86 (용답동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신답','Sindap','02-6110-1351','서울특별시 성동구 천호대로 232 (용답동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('도림천','Dorimcheon','02-6110-2441','서울특별시 구로구 경인로 67길 160 (신도림동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('양천구청','Yangcheon-gu Office','02-6110-2451','서울특별시 양천구 목동로3길 지하 33(신정동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신정네거리','Sinjeongnegeori','02-6110-2461','서울특별시 양천구 중앙로 지하 261 (신정동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('용두','Yongdu','02-6110-1361','서울특별시 동대문구 천호대로 지하 129', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('지축','Jichuk','02-6110-3191','경기도 고양시 덕양구 삼송로 300 (지축동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('구파발','Gupabal','02-6110-3201','서울특별시 은평구 진관2로 지하 15-25 (진관동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('연신내','Yeonsinnae','02-6110-3211','서울특별시 은평구 통일로 지하 849 (갈현동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('불광','Bulgwang','02-6110-3221','서울특별시 은평구 통일로 지하 723-1 (대조동 / 3호선 불광역)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('녹번','Nokbeon','02-6110-3231','서울특별시 은평구 통일로 지하 602-1 (녹번동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('홍제','Hongje','02-6110-3241','서울특별시 서대문구 통일로 지하 440-1 (홍제동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('무악재','Muakjae','02-6110-3251','서울특별시 서대문구 통일로 지하 361 (홍제동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('경복궁','Gyeongbokgung','02-6110-3271','서울특별시 종로구 사직로 지하 130 (적선동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('안국','Anguk','02-6110-3281','서울특별시 종로구 율곡로 지하 62 (안국동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('충무로','Chungmuro','02-6110-4231','서울특별시 중구 퇴계로 지하 199 (필동2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('동대입구','Dongguk Univ.','02-6110-3321','서울특별시 중구 동호로 지하 256 (장충동2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('약수','Yaksu','02-6110-3331','서울특별시 중구 다산로 지하 122 (신당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('금호','Geumho','02-6110-3341','서울특별시 성동구 동호로 지하 104 (금호동4가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('옥수','Oksu','02-6110-3351','서울특별시 성동구 동호로 21 (옥수동) 옥수역', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('압구정','Apgujeong','02-6110-3361','서울특별시 강남구 압구정로 지하 172 (신사동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신사','Sinsa','02-6110-3371','서울특별시 강남구 도산대로 지하 102 (신사동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('잠원','Jamwon','02-6110-3381','서울특별시 서초구 잠원로 4길 지하 46 (잠원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('고속터미널','Express Bus Terminal','02-6110-3391','서울특별시 서초구 신반포로 지하 188 (반포동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('남부터미널','Nambu Bus Terminal','02-6110-3411','서울특별시 서초구 서초중앙로 지하 31 (서초동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('양재','Yangjae','02-6110-3421','서울특별시 서초구 남부순환로 지하 2585 (서초동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('매봉','Maebong','02-6110-3431','서울특별시 강남구 남부순환로 지하 2744 (도곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('도곡','Dogok','02-6110-3441','서울특별시 강남구 남부순환로 지하 2814 (도곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('대치','Daechi','02-6110-3451','서울특별시 강남구 남부순환로 지하 2952 (대치동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('학여울','Hangnyeoul','02-6110-3461','서울특별시 강남구 남부순환로 지하 3104 (대치동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('대청','Daecheong','02-6110-3471','서울특별시 강남구 일원로 지하 2 (일원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('일원','Irwon','02-6110-3481','서울특별시 강남구 일원로 지하 121 (일원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('수서','Suseo','02-6110-3491','서울특별시 강남구 광평로 지하 270 (수서동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('가락시장','Garak Market','02-6311-8171','서울특별시 송파구 송파대로 지하 257 (가락동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('경찰병원','National Police Hospital','02-3110-3511','서울특별시 송파구 중대로 지하 149 (가락동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('오금','Ogeum','02-6110-3521','서울특별시 송파구 오금로 지하 321 (오금동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('당고개','Danggogae','02-6110-4091','서울특별시 노원구 상계로 305 (상계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상계','Sanggye','02-6110-4101','서울특별시 노원구 상계로 182 (상계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('노원','Nowon','02-6110-4111','서울특별시 노원구 상계로 69-1 (상계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('창동','Chang-dong','02-6110-4121','서울특별시 도봉구 마들로 11길 77 (창동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('쌍문','Ssangmun','02-6110-4131','서울특별시 도봉구 도봉로 지하 486-1 (창동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('수유','Suyu','02-6110-4141','서울특별시 강북구 도봉로 지하 50 (미아동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('미아','Mia','02-6110-4151','서울특별시 강북구 도봉로 지하 198 (미아동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('미아사거리','Miasamgeori','02-6110-4161','서울특별시 강북구 도봉로 지하 50 (미아동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('길음','Gireum','02-6110-4171','서울특별시 성북구 동소문로 지하 248 (길음동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('성신여대입구','Sungshin Women`s Univ.','02-6110-4181','서울특별시 성북구 동소문로 지하 102 (동선동4가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('한성대입구','Hansung Univ.','02-6110-4191','서울특별시 성북구 삼선교로 지하1 (삼선동1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('혜화','Hyehwa','02-6110-4201','서울특별시 종로구 대학로 지하 120 (동숭동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('명동','Myeong-dong','02-6110-4241','서울특별시 중구 퇴계로 지하 126 (충무로2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('회현','Hoehyeon','02-6110-4251','서울특별시 중구 퇴계로 지하 54 (남창동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('숙대입구','Sookmyung Women`s Univ.','02-6110-4271','서울특별시 용산구 한강대로 지하 306', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('삼각지','Samgakji','02-6110-4281','서울특별시 용산구 한강대로 지하 180 (한강로1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신용산','Sinyongsan','02-6110-4291','서울특별시 용산구 한강대로 지하 112 (한강로2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('이촌','Ichon','02-6110-4301','서울특별시 용산구 용산동5가 17', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('동작','Dongjak','02-6110-4311','서울특별시 동작구 현충로 257 (동작동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('총신대입구','Chongshin Univ.','02-6110-4321','서울특별시 동작구 동작대로 지하 117 (사당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('남태령','Namtaeryeong','02-6110-4341','서울특별시 서초구 과천대로 지하 816 (방배동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('방화','Banghwa','02-6311-5101','서울특별시 강서구 금낭화로 지하132 (방화동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('개화산','Gaehwasan','02-6311-5111','서울특별시 강서구 양천로 22(방화동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('김포공항','Gimpo Intl. Airport','02-6311-5121','서울특별시 강서구 하늘길 지하77 (방화동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('송정','Songjeong','02-6311-5131','서울특별시 강서구 공항대로 지하33 (공항동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마곡','Magok','02-6311-5141','서울특별시 강서구 공항대로 지하163 (가양동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('발산','Balsan','02-6311-5151','서울특별시 강서구 공항대로 지하267 (가양동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('우장산','Ujangsan','02-6311-5161','서울특별시 강서구 강서로 지하262 (화곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('화곡','Hwagok','02-6311-5171','서울특별시 강서구 화곡로 지하168 (화곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신정','Sinjeong','02-6311-5191','서울특별시 양천구 오목로 지하179 (신정동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('목동','Mok-dong','02-6311-5201','서울특별시 양천구 오목로 지하245 (목동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('오목교','Omokgyo','02-6311-5211','서울특별시 양천구 오목로 지하342 (목동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('양평','Yangpyeong','02-6311-5221','서울특별시 영등포구 양산로 지하21 (양평동2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('영등포시장','Yeongdeungpo Market','02-6311-5241','서울특별시 영등포구 양산로 지하200 (영등포동5가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신길','Singil','02-6311-5251','서울특별시 영등포구 경인로114가길 지하9 (영등포동1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('여의도','Yeouido','02-6311-5261','서울특별시 영등포구 여의나루로 지하40 (여의도동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('여의나루','Yeouinaru','02-6311-5271','서울특별시 영등포구 여의동로 지하343 (여의도동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마포','Mapo','02-6311-5281','서울특별시 마포구 마포대로 지하33 (도화동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('공덕','Gongdeok','02-6311-5291','서울특별시 마포구 마포대로 지하100 (공덕동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('애오개','Aeogae','02-6311-5301','서울특별시 마포구 마포대로 지하210 (아현동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('서대문','Seodaemun','02-6311-5321','서울특별시 종로구 통일로 지하126 (평동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('광화문','Gwanghwamun','02-6311-5331','서울특별시 종로구 세종대로 지하172 (세종로)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('청구','Cheonggu','02-6311-5371','서울특별시 중구 청구로 지하77 (신당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신금호','Singeumho','02-6311-5381','서울특별시 성동구 금호로 지하154 (금호동2가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('행당','Haengdang','02-6311-5391','서울특별시 성동구 행당로 지하89 (행당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마장','Majang','02-6311-5411','서울특별시 성동구 마장로 지하296 (마장동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('답십리','Dapsimni','02-6311-5421','서울특별시 성동구 천호대로 지하300(용답동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('장한평','Janghanpyeong','02-6311-5431','서울특별시 동대문구 천호대로 지하405 (장안동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('군자','Gunja','02-6311-5441','서울특별시 광진구 천호대로 지하550', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('아차산','Achasan','02-6311-5451','서울특별시 광진구 천호대로 지하657', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('광나루','Gwangnaru','02-6311-5461','서울특별시 광진구 아차산로 지하571 (광장동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('천호','Cheonho','02-6311-5471','서울특별시 강동구 천호대로 지하997 (천호동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('강동','Gangdong','02-6311-5481','서울특별시 강동구 천호대로 지하1097 (천호동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('길동','Gil-dong','02-6311-5491','서울특별시 강동구 양재대로 지하1480 (길동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('굽은다리','Gubeundari','02-6311-5501','서울특별시 강동구 양재대로 지하1572 (명일동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('명일','Myeongil','02-6311-5511','서울특별시 강동구 양재대로 지하1632 (명일동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('고덕','Godeok','02-6311-5521','서울특별시 강동구 고덕로 지하253 (고덕동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상일동','Sangil-dong','02-6311-5531','서울특별시 강동구 고덕로 지하359 (상일동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('둔촌동','Dunchon-dong','02-6311-5541','서울특별시 강동구 양재대로 지하1369 (둔촌동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('올림픽공원','Olympic Park','02-6311-5551','서울특별시 송파구 양재대로 지하1233', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('방이','Bangi','02-6311-5561','서울특별시 송파구 양재대로 지하1127 (방이동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('개롱','Gaerong','02-6311-5581','서울특별시 송파구 오금로 지하402 (가락동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('거여','Geoyeo','02-6311-5591','서울특별시 송파구 오금로 지하499 (거여동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마천','Macheon','02-6311-5601','서울특별시 송파구 마천로57길 지하7 (마천동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('응암','Eungam','02-6311-6101','서울특별시 은평구 증산로 지하477 (역촌동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('역촌','Yeokchon','02-6311-6111','서울특별시 은평구 서오릉로 지하63 (녹번동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('독바위','Dokbawi','02-6311-6131','서울특별시 은평구 불광로 지하129-1 (불광동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('구산','Gusan','02-6311-6151','서울특별시 은평구 연서로 지하137-1 (구산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('새절','Saejeol','02-6311-6161','서울특별시 은평구 증산로 지하400 (신사동', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('증산','Jeungsan','02-6311-6171','서울특별시 은평구 증산로 지하306 (증산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('디지털미디어시티','Digital Media City','02-6311-6181','서울특별시 은평구 수색로 지하175 (증산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('월드컵경기장','World Cup Stadium','02-6311-6191','서울특별시 마포구 월드컵로 지하240 (성산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마포구청','Mapo-gu Office','02-6311-6201','서울특별시 마포구 월드컵로 지하190 (성산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('망원','Mangwon','02-6311-6211','서울특별시 마포구 월드컵로 지하77 (망원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상수','Sangsu','02-6311-6231','서울특별시 마포구 독막로 지하85 (상수동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('광흥창','Gwangheungchang','02-6311-6241','서울특별시 마포구 독막로 지하 165', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('대흥','Daeheung','02-6311-6251','서울특별시 마포구 대흥로 지하 85', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('효창공원앞','Hyochang park','02-6311-6271','서울특별시 용산구 백범로 지하287 (효창동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('녹사평','Noksapyeong','02-6311-6291','서울특별시 용산구 녹사평대로 지하195 (용산동4가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('이태원','Itaewon','02-6311-6301','서울특별시 용산구 이태원로 지하177 (이태원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('한강진','Hangangjin','02-6311-6311','서울특별시 용산구 이태원로 지하287 (한남동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('버티고개','Beotigogae','02-6311-6321','서울특별시 중구 다산로 지하38 (신당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('창신','Changsin','02-6311-6371','서울특별시 종로구 지봉로 지하112 (창신동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('보문','Bomun','02-6311-6381','서울특별시 성북구 보문로 지하116 (보문동1가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('안암','Anam','02-6311-6391','서울특별시 성북구 고려대로 지하89 (안암동5가)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('고려대','Korea Univ.','02-6311-6401','서울특별시 성북구 종암로 지하1 (종암동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('월곡','Wolgok','02-6311-6411','서울특별시 성북구 월곡로 지하107 (하월곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상월곡','Sangwolgok','02-6311-6421','서울특별시 성북구 화랑로 지하157 (상월곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('돌곶이','Dolgoji','02-6311-6431','서울특별시 성북구 화랑로 지하243 (석관동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('석계','Seokgye','02-6311-6441','서울특별시 노원구 화랑로 지하347-1 (월계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('태릉입구','Taereung','02-6311-7171','서울특별시 노원구 동일로 지하992-1 (공릉동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('화랑대','Hwarangdae','02-6311-6461','서울특별시 노원구 화랑로 지하510', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('봉화산','Bonghwasan','02-6311-6471','서울특별시 중랑구 신내로 지하232 (신내동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신내','Sinnae','02-6311-6481','서울특별시 중랑구 용마산로136길 33', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('장암','Jangam','02-6311-7091','경기도 의정부시 동일로 121 (장암동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('도봉산','Dobongsan','02-6311-7101','서울특별시 도봉구 도봉로 964-40 (도봉동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('수락산','Suraksan','02-6311-7111','서울특별시 노원구 동일로 지하1662 (상계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('마들','Madeul','02-6311-7121','서울특별시 노원구 동일로 지하1530-1 (상계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('중계','Junggye','02-6311-7141','서울특별시 노원구 동일로 지하1308-1 (중계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('하계','Hagye','02-6311-7151','서울특별시 노원구 동일로 지하1196 (하계동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('공릉','Gongneung','02-6311-7161','서울특별시 노원구 동일로 지하1074', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('먹골','Meokgol','02-6311-7181','서울특별시 중랑구 동일로 지하901 (묵동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('중화','Junghwa','02-6311-7191','서울특별시 중랑구 동일로 지하797 (중화동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상봉','Sangbong','02-6311-7201','서울특별시 중랑구 망우로 지하 297', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('면목','Myeonmok','02-6311-7211','서울특별시 중랑구 면목로 지하407(면목동 / 면목역)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('사가정','Sagajeong','02-6311-7221','서울특별시 중랑구 사가정로 지하393 (면목동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('용마산','Yongmasan','02-6311-7231','서울특별시 중랑구 용마산로 지하227 (면목동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('중곡','Junggok','02-6311-7241','서울특별시 광진구 능동로 지하417 (중곡동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('어린이대공원','Children`s  Grand Park','02-6311-7261','서울특별시 광진구 능동로 지하210 (화양동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('뚝섬유원지','Ttukseom Park','02-6311-7281','서울특별시 광진구 능동로 10 (자양동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('청담','Cheongdam','02-6311-7291','서울특별시 강남구 학동로 지하508 (청담동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('강남구청','Gangnam-gu Office','02-6311-7301','서울특별시 강남구 학동로 지하346 (삼성동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('학동','Hak-dong','02-6311-7311','서울특별시 강남구 학동로 지하180 (논현동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('논현','Nonhyeon','02-6311-7321','서울특별시 강남구 학동로 지하102(논현동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('반포','Banpo','02-6311-7331','서울특별시 서초구 신반포로 지하241(잠원동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('내방','Naebang','02-6311-7351','서울특별시 서초구 서초대로 지하103 (방배동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('이수','Isu','02-6311-7361','서울특별시 동작구 사당로 지하310 (사당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('남성','Namseong','02-6311-7371','서울특별시 동작구 사당로 지하218 (사당동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('숭실대입구','Soongsil Univ.','02-6311-7381','서울특별시 동작구 상도로 지하 378', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상도','Sangdo','02-6311-7392','서울특별시 동작구 상도로 지하272 (상도1동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('장승배기','Jangseungbaegi','02-6311-7401','서울특별시 동작구 상도로 지하188 (상도동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신대방삼거리','Sindaebangsamgeori','02-6311-7411','서울특별시 동작구 상도로 지하76 (대방동) ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('보라매','Boramae','02-6311-7421','서울특별시 동작구 상도로 지하2 (대방동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신풍','Sinpung','02-6311-7431','서울특별시 영등포구 신풍로 지하27 (신길동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('남구로','Namguro','02-6311-7451','서울특별시 구로구 도림로 지하7 (구로동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('가산디지털단지','Gasan Digital Complex','02-6311-7461','서울특별시 금천구 벚꽃로 309 (가산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('철산','Cheolsan','02-6311-7471','경기도 광명시 철산로 지하13 (철산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('광명사거리','Gwangmyeongsageori','02-6311-7481','경기도 광명시 오리로 지하980(광명동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('천왕','Cheonwang','02-6311-7491','서울특별시 구로구 오리로 지하1154(오류동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('온수','Onsu','02-6311-7501','서울특별시 구로구 경인로3길 지하64 (온수동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('까치울','Kkachiul','02-6311-7511','경기도 부천시 길주로 626 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('부천종합운동장','Bucheon Stadium','02-6311-7521','경기도 부천시 길주로 지하 502 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('춘의','Chunui','02-6311-7531','경기도 부천시 길주로 지하 406 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신중동','Sinjung-dong','02-6311-7541','경기도 부천시 길주로 314 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('부천시청','Bucheon City Hall','02-6311-7551','경기도 부천시 길주로 202 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('상동','Sang-dong','02-6311-7561','경기도 부천시 길주로 104 ', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('삼산체육관','Samsan Gymnasium','02-6311-7571','인천광역시 부평구 길주로 지하713 (삼산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('굴포천','Gulpocheon','02-6311-7581','인천광역시 부평구 길주로 지하623 (삼산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('부평구청','Bupyeong-gu Office','02-6311-7591','인천광역시 부평구 길주로 지하527(갈산동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('암사','Amsa','02-6311-8101','서울특별시 강동구 올림픽로 지하776 (암사동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('강동구청','Gangdong-gu Office','02-6311-8121','서울특별시 강동구 올림픽로 지하550 (성내동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('몽촌토성','Mongchontoseong','02-6311-8131','서울특별시 송파구 올림픽로 지하383', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('석촌','Seokchon','02-6311-8151','서울특별시 송파구 송파대로 지하439 (석촌동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('송파','Songpa','02-6311-8161','서울특별시 송파구 송파대로 지하354 (가락동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('문정','Munjeong','02-6311-8181','서울특별시 송파구 송파대로 지하179 (문정동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('장지','Jangji','02-6311-8191','서울특별시 송파구 송파대로 지하82 (장지동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('복정','Bokjeong','02-6311-8201','서울특별시 송파구 송파대로 지하6 (장지동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('산성','Sanseong','02-6311-8211','경기도 성남시 수정구 수정로 지하365(신흥동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('남한산성입구','Namhansanseong','02-6311-8221','경기도 성남시 수정구 산성대로 지하 445', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('단대오거리','Dandaeogeori','02-6311-8231','경기도 성남시 수정구 산성대로 지하365 (신흥동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('신흥','Sinheung','02-6311-8241','경기도 성남시 수정구 산성대로 지하280 (신흥동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('수진','Sujin','02-6311-8251','경기도 성남시 수정구 산성대로 지하200 (수진동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('모란','Moran','02-6311-8261','경기도 성남시 수정구 산성대로 지하100 (수진동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('언주','Eonju','02-2656-0926','서울특별시 강남구 봉은사로 지하 201', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('선정릉','Seonjeongneung','02-2656-0927','서울특별시 강남구 선릉로 지하 580', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('삼성중앙','Samseong Jungang','02-2656-0928','서울특별시 강남구 봉은사로 지하 501', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('봉은사','Bongeunsa','02-2656-0929','서울특별시 강남구 봉은사로 지하 601', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('삼전','Samjeon','02-2656-0931','서울특별시 송파구 백제고분로 187', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('석촌고분','Seokchon Gobun','02-2656-0932','서울특별시 송파구 삼학사로 53', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('송파나루','Songpanaru','02-2656-0934','서울특별시 송파구 오금로 165', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('한성백제','Hanseong Baekje','02-2656-0935','서울특별시 송파구 위례성대로 51', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('둔촌오륜','Dunchon Oryun','02-2656-0937','서울특별시 송파구 강동대로 327', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('중앙보훈병원','VHS Medical Center','02-2656-0938','서울특별시 강동구 명일로 117', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('선릉','Seolleung','02-6110-2201','서울특별시 강남구 테헤란로 지하 340 (삼성동)', , );
INSERT INTO station (ID,ENAME,PHONE,ADDRESS, X_COORD, Y_COORD) VALUES ('독립문','Dongnimmun','02-6110-3261','서울특별시 서대문구 통일로 지하 247 (현저동)', , );
