INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(1, 0, '1호선 본선', 1001);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(2, 0, '2호선 본선', 1002);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(2, 1, '2호선 성수 지선', 1002);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(2, 2, '2호선 신정 지선', 1002);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(3, 0, '3호선 본선', 1003);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(4, 0, '4호선 본선', 1004);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(5, 0, '5호선 본선', 1005);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(5, 1, '5호선 마천 지선', 1005);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(6, 0, '6호선 본선', 1006);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(7, 0, '7호선 본선', 1007);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(8, 0, '8호선 본선', 1008);
INSERT INTO subway_line_detail(line, subline, name, subway_code) VALUES(9, 0, '9호선 본선', 1009);
